version: 2
updates:

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/rc"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "[docker] "