name: Docker build

on:
  push:
    branches:
      - master
    paths:
    - build-image/*
    - src/**
    - .github/workflows/docker-build.yml

env:
  config: Release

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install XMLLint
      run: | 
        sudo apt-get update
        sudo apt-get install libxml2-utils
    - name: Get tagname
      run: echo "build_number=$(./version.sh)" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: sebagomez
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        tags: latest,${{ env.build_number }}
        build-args: BUILD=${{ env.build_number }}
        context: ./src
        push: true 
