name: Build

on:
  push:
    paths:
    - build-image/*
    - src/**
    - .github/workflows/dotnet-core.yml
  pull_request:
    paths:
    - src/**
    - .github/workflows/dotnet-core.yml

env:
  config: Release
  solution: ./AzureWebExplorer.sln

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Local Build
      run: dotnet build --configuration Release ./src/AzureWebStorageExplorer/AzureWebStorageExplorer.csproj

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v2
    - name: Install XMLLint
      run: sudo apt-get install libxml2-utils
    - name: Get tagname
      run: echo "build_number=$(./version.sh)" >> $GITHUB_ENV
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.1
      with:
        username: sebagomez
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest,${{ env.build_number }}
        build_args: BUILD=${{ env.build_number }}
        add_git_labels: false
        path: ./src
        push: true 
