name: Build

on:
  push:
    paths:
    - ./src/**
    - ./.github/workflows
  pull_request:
    paths:
    - ./src/**
    - ./.github/workflows

env:
  config: Release
  solution: ./AzureWebExplorer.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set current date as env variable
      run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.1
      with:
        username: sebagomez
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sebagomez/azurestorageexplorer
        tags: latest,$NOW
        build_args: BUILD=$NOW
        add_git_labels: true
        path: ./src
        push: true 
