name: Build

on:
  push:
    paths:
    - ./src/**
    - ./.github/workflows
  pull_request:
    paths:
    - ./src/**
    - ./.github/workflows

env:
  config: Release
  solution: ./AzureWebExplorer.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies $solution
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration $config --no-restore $solution
    - name: Publish
      run: dotnet publish -o ./Docker/root --configuration $config --no-build $solution 
# - name: Test
#   run: dotnet test --no-restore --verbosity normal
