name: Build

on:
  push:
    paths:
    - src/**
    - .github/workflows/dotnet-core.yml
  pull_request:
    paths:
    - src/**
    - .github/workflows/dotnet-core.yml

env:
  config: Release
  solution: ./AzureWebExplorer.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.1
      with:
        username: sebagomez
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sebagomez/azurestorageexplorer
        tags: latest,${{ github.run_id }}
        build_args: BUILD=${{ github.run_id }}
        add_git_labels: true
        path: ./src
        push: true 
