name: Build

on:
  push:
    paths:
    - src/**
    - .github/workflows/dotnet-core.yml
  pull_request:
    paths:
    - src/**
    - .github/workflows/dotnet-core.yml

env:
  config: Release
  solution: ./AzureWebExplorer.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get tagname
      run: |
      currDate=$(date +%Y%m%d%H%M)
      echo "::set-env name=build_number::$(currDate)"
      echo Build_Number: $build_number
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.1
      with:
        username: sebagomez
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest,${{ env.build_number }}
        build_args: BUILD=${{ env.build_number }}
        add_git_labels: true
        path: ./src
        push: true 
